// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nathancastelein/go-architecture-hexagonale-gaule/internal/panoramix/cuisson (interfaces: Appareil)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/appareil.go -package cuissonmocks . Appareil
//

// Package cuissonmocks is a generated GoMock package.
package cuissonmocks

import (
	reflect "reflect"

	recette "github.com/nathancastelein/go-architecture-hexagonale-gaule/internal/panoramix/recette"
	gomock "go.uber.org/mock/gomock"
)

// MockAppareil is a mock of Appareil interface.
type MockAppareil struct {
	ctrl     *gomock.Controller
	recorder *MockAppareilMockRecorder
	isgomock struct{}
}

// MockAppareilMockRecorder is the mock recorder for MockAppareil.
type MockAppareilMockRecorder struct {
	mock *MockAppareil
}

// NewMockAppareil creates a new mock instance.
func NewMockAppareil(ctrl *gomock.Controller) *MockAppareil {
	mock := &MockAppareil{ctrl: ctrl}
	mock.recorder = &MockAppareilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppareil) EXPECT() *MockAppareilMockRecorder {
	return m.recorder
}

// Cuire mocks base method.
func (m *MockAppareil) Cuire(ingrédient recette.Ingrédient, ingrédientObtenu string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cuire", ingrédient, ingrédientObtenu)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cuire indicates an expected call of Cuire.
func (mr *MockAppareilMockRecorder) Cuire(ingrédient, ingrédientObtenu any) *MockAppareilCuireCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cuire", reflect.TypeOf((*MockAppareil)(nil).Cuire), ingrédient, ingrédientObtenu)
	return &MockAppareilCuireCall{Call: call}
}

// MockAppareilCuireCall wrap *gomock.Call
type MockAppareilCuireCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppareilCuireCall) Return(arg0 error) *MockAppareilCuireCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppareilCuireCall) Do(f func(recette.Ingrédient, string) error) *MockAppareilCuireCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppareilCuireCall) DoAndReturn(f func(recette.Ingrédient, string) error) *MockAppareilCuireCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Préchauffer mocks base method.
func (m *MockAppareil) Préchauffer(température recette.Température) chan bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Préchauffer", température)
	ret0, _ := ret[0].(chan bool)
	return ret0
}

// Préchauffer indicates an expected call of Préchauffer.
func (mr *MockAppareilMockRecorder) Préchauffer(température any) *MockAppareilPréchaufferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Préchauffer", reflect.TypeOf((*MockAppareil)(nil).Préchauffer), température)
	return &MockAppareilPréchaufferCall{Call: call}
}

// MockAppareilPréchaufferCall wrap *gomock.Call
type MockAppareilPréchaufferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppareilPréchaufferCall) Return(arg0 chan bool) *MockAppareilPréchaufferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppareilPréchaufferCall) Do(f func(recette.Température) chan bool) *MockAppareilPréchaufferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppareilPréchaufferCall) DoAndReturn(f func(recette.Température) chan bool) *MockAppareilPréchaufferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prélever mocks base method.
func (m *MockAppareil) Prélever() recette.Ingrédient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prélever")
	ret0, _ := ret[0].(recette.Ingrédient)
	return ret0
}

// Prélever indicates an expected call of Prélever.
func (mr *MockAppareilMockRecorder) Prélever() *MockAppareilPréleverCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prélever", reflect.TypeOf((*MockAppareil)(nil).Prélever))
	return &MockAppareilPréleverCall{Call: call}
}

// MockAppareilPréleverCall wrap *gomock.Call
type MockAppareilPréleverCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppareilPréleverCall) Return(arg0 recette.Ingrédient) *MockAppareilPréleverCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppareilPréleverCall) Do(f func() recette.Ingrédient) *MockAppareilPréleverCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppareilPréleverCall) DoAndReturn(f func() recette.Ingrédient) *MockAppareilPréleverCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VérifierTempérature mocks base method.
func (m *MockAppareil) VérifierTempérature() recette.Température {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VérifierTempérature")
	ret0, _ := ret[0].(recette.Température)
	return ret0
}

// VérifierTempérature indicates an expected call of VérifierTempérature.
func (mr *MockAppareilMockRecorder) VérifierTempérature() *MockAppareilVérifierTempératureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VérifierTempérature", reflect.TypeOf((*MockAppareil)(nil).VérifierTempérature))
	return &MockAppareilVérifierTempératureCall{Call: call}
}

// MockAppareilVérifierTempératureCall wrap *gomock.Call
type MockAppareilVérifierTempératureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppareilVérifierTempératureCall) Return(arg0 recette.Température) *MockAppareilVérifierTempératureCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppareilVérifierTempératureCall) Do(f func() recette.Température) *MockAppareilVérifierTempératureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppareilVérifierTempératureCall) DoAndReturn(f func() recette.Température) *MockAppareilVérifierTempératureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
