// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nathancastelein/go-architecture-hexagonale-gaule/internal/panoramix/druide (interfaces: Druide)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/druide.go -package druidemocks . Druide
//

// Package druidemocks is a generated GoMock package.
package druidemocks

import (
	reflect "reflect"

	recette "github.com/nathancastelein/go-architecture-hexagonale-gaule/internal/panoramix/recette"
	gomock "go.uber.org/mock/gomock"
)

// MockDruide is a mock of Druide interface.
type MockDruide struct {
	ctrl     *gomock.Controller
	recorder *MockDruideMockRecorder
	isgomock struct{}
}

// MockDruideMockRecorder is the mock recorder for MockDruide.
type MockDruideMockRecorder struct {
	mock *MockDruide
}

// NewMockDruide creates a new mock instance.
func NewMockDruide(ctrl *gomock.Controller) *MockDruide {
	mock := &MockDruide{ctrl: ctrl}
	mock.recorder = &MockDruideMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDruide) EXPECT() *MockDruideMockRecorder {
	return m.recorder
}

// Préparer mocks base method.
func (m *MockDruide) Préparer(arg0 recette.Recette) (*recette.Plat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Préparer", arg0)
	ret0, _ := ret[0].(*recette.Plat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Préparer indicates an expected call of Préparer.
func (mr *MockDruideMockRecorder) Préparer(arg0 any) *MockDruidePréparerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Préparer", reflect.TypeOf((*MockDruide)(nil).Préparer), arg0)
	return &MockDruidePréparerCall{Call: call}
}

// MockDruidePréparerCall wrap *gomock.Call
type MockDruidePréparerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDruidePréparerCall) Return(arg0 *recette.Plat, arg1 error) *MockDruidePréparerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDruidePréparerCall) Do(f func(recette.Recette) (*recette.Plat, error)) *MockDruidePréparerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDruidePréparerCall) DoAndReturn(f func(recette.Recette) (*recette.Plat, error)) *MockDruidePréparerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
